function fix_instrument_decision(modelName)
% FIX_INSTRUMENT_DECISION  Removes the duplicate "Instrument Decision"
%   block added by the installer script and updates the TRACE function
%   inside the original "INSTRUMENT DECISION" with the full INOAS
%   deactivation + reactivation logic (Sections 5.2.2 and 7.4).
%
% USAGE (run once):
%   fix_instrument_decision('MPCcontrolledSpacecraft_plant_gnss_with_predictor')
%
% WHAT THIS DOES:
%   1. Removes the duplicate "Instrument Decision" subsystem (mixed case)
%      and its helpers: Lambda Scope, x_gnss_zero, gnss_avail_flag
%   2. Replaces the TRACE MATLAB Function script inside the original
%      all-caps "INSTRUMENT DECISION" with the full GNSS duty-cycling
%      logic (deactivation + reactivation state machine)

    if nargin < 1; modelName = 'MPCcontrolledSpacecraft_plant_gnss_with_predictor'; end
    modelName = char(modelName);

    if ~bdIsLoaded(modelName); load_system(modelName); end
    fprintf('Loaded: %s\n', modelName);

    %----------------------------------------------------------------------
    % STEP 1 – Remove the duplicate block and its helpers
    %----------------------------------------------------------------------
    blocksToDelete = {
        [modelName, '/Instrument Decision'],   % duplicate (mixed case)
        [modelName, '/Lambda Scope'],
        [modelName, '/x_gnss_zero'],
        [modelName, '/gnss_avail_flag'],
        [modelName, '/Goto_lambda'],
    };

    for k = 1:numel(blocksToDelete)
        bp = blocksToDelete{k};
        if getSimulinkBlockHandle(bp) ~= -1
            % Delete connected lines first
            try
                ph = get_param(bp, 'PortHandles');
                allPorts = [ph.Inport, ph.Outport];
                for p = 1:numel(allPorts)
                    lh = get_param(allPorts(p), 'Line');
                    if lh ~= -1; delete_line(lh); end
                end
            catch; end
            delete_block(bp);
            fprintf('  Deleted: %s\n', bp);
        end
    end

    % Also remove the From_lambda block that may have been added inside
    % the GNSS subsystem
    gnssBlock = find_gnss_block(modelName);
    if ~isempty(gnssBlock)
        fromLambda = [gnssBlock, '/From_lambda'];
        if getSimulinkBlockHandle(fromLambda) ~= -1
            try
                ph = get_param(fromLambda, 'PortHandles');
                lh = get_param(ph.Outport, 'Line');
                if lh ~= -1; delete_line(lh); end
            catch; end
            delete_block(fromLambda);
            fprintf('  Deleted: %s\n', fromLambda);
        end
    end

    fprintf('Step 1 done – duplicate removed.\n\n');

    %----------------------------------------------------------------------
    % STEP 2 – Update the TRACE MATLAB Function inside INSTRUMENT DECISION
    %----------------------------------------------------------------------
    % Find the original all-caps block
    origBlock = find_original_instrument_decision(modelName);
    if isempty(origBlock)
        error('Could not find the original INSTRUMENT DECISION block.');
    end
    fprintf('Original block found: %s\n', origBlock);

    % Find the TRACE MATLAB Function inside it
    traceBlock = find_trace_block(origBlock);
    if isempty(traceBlock)
        error('Could not find the TRACE MATLAB Function inside %s.', origBlock);
    end
    fprintf('TRACE block found: %s\n', traceBlock);

    % Write the new script
    newScript = build_trace_script();
    set_matlab_function_script(traceBlock, newScript);
    fprintf('Step 2 done – TRACE function updated with full INOAS logic.\n\n');

    %----------------------------------------------------------------------
    % STEP 3 – Save
    %----------------------------------------------------------------------
    save_system(modelName);
    fprintf('Saved: %s.slx\n', modelName);
    fprintf('\n--- Summary ---\n');
    fprintf('The original INSTRUMENT DECISION block now implements:\n');
    fprintf('  - GNSS deactivation: N_hold=60, sigma_enter=65m, N_good=120\n');
    fprintf('  - KF reactivation:   alpha=0.98, eta_th=0.5, N_bad=25, N_refresh=2000\n');
    fprintf('All existing wiring to KALMAN FILTER and GNSS blocks is preserved.\n');
end

%==========================================================================
% BLOCK FINDERS
%==========================================================================

function blk = find_original_instrument_decision(modelName)
% Finds the original all-caps INSTRUMENT DECISION block.
    blk = [];
    candidates = find_system(modelName, 'SearchDepth', 1, 'BlockType', 'SubSystem');
    for k = 1:numel(candidates)
        name = get_param(candidates{k}, 'Name');
        % Match all-caps version, ignore the duplicate we just deleted
        if strcmpi(name, 'INSTRUMENT DECISION') && ...
           ~strcmp(name, 'Instrument Decision')
            blk = candidates{k};
            return;
        end
    end
    % Fallback: any subsystem with 'instrument' in name
    for k = 1:numel(candidates)
        name = lower(get_param(candidates{k}, 'Name'));
        if contains(name, 'instrument')
            blk = candidates{k};
            return;
        end
    end
end

function blk = find_trace_block(parentBlock)
% Finds the MATLAB Function (TRACE) block inside INSTRUMENT DECISION.
    blk = [];
    candidates = find_system(parentBlock, 'SearchDepth', 1, 'BlockType', 'SubSystem');
    for k = 1:numel(candidates)
        if strcmp(candidates{k}, parentBlock); continue; end
        sfType = get_param(candidates{k}, 'SFBlockType');
        if strcmpi(sfType, 'MATLAB Function')
            blk = candidates{k};
            return;
        end
    end
end

function blk = find_gnss_block(modelName)
    blk = [];
    candidates = find_system(modelName, 'SearchDepth', 1, 'BlockType', 'SubSystem');
    for k = 1:numel(candidates)
        name = lower(get_param(candidates{k}, 'Name'));
        if contains(name, 'gnss') || contains(name, 'activaci')
            blk = candidates{k};
            return;
        end
    end
end

%==========================================================================
% MATLAB FUNCTION SCRIPT WRITER
%==========================================================================

function set_matlab_function_script(blockPath, scriptText)
    rt = sfroot;
    charts = rt.find('-isa', 'Stateflow.EMChart');
    for k = 1:numel(charts)
        if strcmp(charts(k).Path, blockPath)
            charts(k).Script = scriptText;
            fprintf('  Script written to: %s\n', blockPath);
            return;
        end
    end
    warning('Could not find EMChart for: %s', blockPath);
end

%==========================================================================
% THE NEW TRACE FUNCTION SCRIPT
%
% The original INSTRUMENT DECISION feeds the TRACE block a pre-processed
% covariance (after the S_T_inv and S_inv Gain blocks).
% We keep that same interface:
%   Input 1: processed matrix  (result of S_T_inv * Pk * S_inv)
%   Output 1: O (trace scalar, for monitoring)
%   Output 2: lamda (0 = KF primary, 1 = GNSS ON)
%
% The full deactivation + reactivation state machine is implemented here.
%==========================================================================

function s = build_trace_script()
s = [
'function [O, lamda] = TRACE(u)', newline, ...
'%TRACE  INOAS Instrument Decision Logic (GNSS duty-cycling).', newline, ...
'% Implements Sections 5.2.2 and 7.4 of the INOAS report.', newline, ...
'%', newline, ...
'% Input:', newline, ...
'%   u       - processed covariance matrix (after S_T_inv * Pk * S_inv), 6x6', newline, ...
'%', newline, ...
'% Outputs:', newline, ...
'%   O       - scalar trace of u  (for monitoring / scope)', newline, ...
'%   lamda   - 1 = GNSS ON,  0 = KF primary', newline, ...
'', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% Parameters', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% --- Deactivation (GNSS -> KF) ---', newline, ...
'N_hold       = int32(60);    % min GNSS-on epochs before deactivation', newline, ...
'sigma_enter  = 65.0;         % position std threshold [m]', newline, ...
'N_good_min   = int32(120);   % persistence window [epochs]', newline, ...
'', newline, ...
'% --- Reactivation (KF -> GNSS) ---', newline, ...
'alpha        = 0.98;         % EMA smoothing factor', newline, ...
'sigma_pos_th = 120.0;        % absolute position limit [m]', newline, ...
'sigma_vel_th = 50.0;         % absolute velocity limit [m/s]', newline, ...
'growth_th    = 1.5;          % relative-growth threshold', newline, ...
'eta_th       = 0.5;          % severity threshold', newline, ...
'N_hold_KF    = int32(50);    % min KF epochs before severity checked', newline, ...
'N_refresh    = int32(2000);  % mandatory GNSS refresh [epochs]', newline, ...
'N_bad_min    = int32(25);    % bad-health persistence', newline, ...
'eps_f        = 1e-6;', newline, ...
'', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% Persistent state', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'persistent lamda_prev', newline, ...
'persistent active_count good_count           % deactivation counters', newline, ...
'persistent sp_sm sv_sm sp_mn sv_mn nKF bc   % reactivation state', newline, ...
'', newline, ...
'if isempty(lamda_prev)', newline, ...
'    lamda_prev   = 1.0;', newline, ...
'    active_count = int32(0);  good_count = int32(0);', newline, ...
'    sp_sm = 0; sv_sm = 0; sp_mn = Inf; sv_mn = Inf;', newline, ...
'    nKF = int32(0);  bc = int32(0);', newline, ...
'end', newline, ...
'', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% Monitoring output: trace of the processed covariance', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'O = u(1,1) + u(2,2) + u(3,3) + u(4,4) + u(5,5) + u(6,6);', newline, ...
'', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% Extract position covariance from the processed matrix', newline, ...
'% (u = S_T_inv * Pk * S_inv, so the pos block is u(1:3,1:3))', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'Pr = u(1:3, 1:3);', newline, ...
'Pr = 0.5*(Pr + Pr'');', newline, ...
'Pv = u(4:6, 4:6);', newline, ...
'Pv = 0.5*(Pv + Pv'');', newline, ...
'', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% BRANCH A – GNSS is currently ON: deactivation logic', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'if lamda_prev >= 0.5', newline, ...
'', newline, ...
'    active_count = active_count + int32(1);', newline, ...
'    m = sqrt(max(Pr(1,1)+Pr(2,2)+Pr(3,3), 0.0));   % position std [m]', newline, ...
'', newline, ...
'    lamda = 1.0;    % default: stay on', newline, ...
'', newline, ...
'    if active_count >= N_hold', newline, ...
'        if m <= sigma_enter', newline, ...
'            good_count = good_count + int32(1);', newline, ...
'        else', newline, ...
'            good_count = int32(0);', newline, ...
'        end', newline, ...
'', newline, ...
'        if good_count >= N_good_min', newline, ...
'            lamda        = 0.0;    % switch GNSS OFF', newline, ...
'            active_count = int32(0);', newline, ...
'            good_count   = int32(0);', newline, ...
'            % Reset reactivation state for fresh KF cycle', newline, ...
'            sp_sm = 0; sv_sm = 0; sp_mn = Inf; sv_mn = Inf;', newline, ...
'            nKF = int32(0); bc = int32(0);', newline, ...
'        end', newline, ...
'    end', newline, ...
'', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% BRANCH B – KF is primary: reactivation logic', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'else', newline, ...
'', newline, ...
'    nKF = nKF + int32(1);', newline, ...
'', newline, ...
'    % Covariance health check', newline, ...
'    cov_ok = all(isfinite(u(:))) && all(diag(u) > 0);', newline, ...
'', newline, ...
'    % Raw uncertainty metrics', newline, ...
'    sr = sqrt(max(Pr(1,1)+Pr(2,2)+Pr(3,3), 0.0));', newline, ...
'    vr = sqrt(max(Pv(1,1)+Pv(2,2)+Pv(3,3), 0.0));', newline, ...
'', newline, ...
'    % Exponential smoothing', newline, ...
'    sp_sm = alpha*sp_sm + (1-alpha)*sr;', newline, ...
'    sv_sm = alpha*sv_sm + (1-alpha)*vr;', newline, ...
'    if sp_sm < sp_mn; sp_mn = sp_sm; end', newline, ...
'    if sv_sm < sv_mn; sv_mn = sv_sm; end', newline, ...
'', newline, ...
'    % Severity metric (Eq. 5.17)', newline, ...
'    eta = max([sp_sm/sigma_pos_th, ...', newline, ...
'               sv_sm/sigma_vel_th, ...', newline, ...
'               sp_sm/max(sp_mn,eps_f)/growth_th, ...', newline, ...
'               sv_sm/max(sv_mn,eps_f)/growth_th]);', newline, ...
'', newline, ...
'    % KF-bad condition (Eq. 5.24)', newline, ...
'    kf_bad = ~cov_ok || ...', newline, ...
'             nKF >= N_refresh || ...', newline, ...
'             (nKF >= N_hold_KF && eta >= eta_th);', newline, ...
'', newline, ...
'    if kf_bad', newline, ...
'        bc = bc + int32(1);', newline, ...
'    else', newline, ...
'        bc = int32(max(double(bc)-1, 0));', newline, ...
'    end', newline, ...
'', newline, ...
'    lamda = 0.0;   % default: stay KF primary', newline, ...
'', newline, ...
'    if bc >= N_bad_min', newline, ...
'        lamda        = 1.0;    % reactivate GNSS', newline, ...
'        sp_sm = 0; sv_sm = 0; sp_mn = Inf; sv_mn = Inf;', newline, ...
'        nKF = int32(0); bc = int32(0);', newline, ...
'        % Reset deactivation counters for fresh GNSS cycle', newline, ...
'        active_count = int32(0); good_count = int32(0);', newline, ...
'    end', newline, ...
'', newline, ...
'end   % branch A/B', newline, ...
'', newline, ...
'lamda_prev = lamda;', newline, ...
'end'];
end
