%% unify_NIS_and_TRACE.m
% =========================================================================
% INOAS - Unify NIS and TRACE into a single decision block
%
% What this script does inside INSTRUMENT DECISION1:
%   1. Updates the NIS MATLAB function with the unified logic
%      (NIS statistical check + TRACE covariance backstop in one function)
%   2. Deletes the wire: TRACE/out:2 --> Switch/in:3
%   3. Adds a new Constant block with value 1
%   4. Connects Constant(1) --> Switch/in:3
%   5. Deletes TRACE subsystem and its connected wires
%   6. Deletes Gain and Gain1 blocks (they only fed TRACE) and their wires
%   7. Deletes Scope connected to TRACE (Scope, SID 233)
%
% The unified compute_NIS now outputs:
%   out:1 = score (NIS scalar, for Scope1 monitoring)
%   out:2 = lamda (binary, 1=GNSS on, 0=KF)
%
% Requires: model already loaded in Simulink
% =========================================================================

modelName = 'MPCcontrolledSpacecraft_plant_gnss_with_predictor';
idPath    = [modelName '/INSTRUMENT DECISION1'];

%% -------------------------------------------------------------------------
% 0. Load model
%% -------------------------------------------------------------------------
fprintf('============================================================\n');
fprintf(' unify_NIS_and_TRACE.m\n');
fprintf('============================================================\n\n');

if ~bdIsLoaded(modelName)
    load_system(modelName);
    fprintf('[LOAD] Model loaded.\n');
else
    fprintf('[LOAD] Model already loaded.\n');
end

if strcmp(get_param(modelName, 'SimulationMode'), 'accelerator')
    set_param(modelName, 'SimulationMode', 'normal');
end

%% -------------------------------------------------------------------------
% Helper: find a block inside INSTRUMENT DECISION1 by name
%% -------------------------------------------------------------------------
findID = @(name) find_system(idPath, 'SearchDepth', 1, 'Name', name);

%% -------------------------------------------------------------------------
% 1. Update the NIS MATLAB function with the unified code
%    The function is a MATLAB Function block (Stateflow S-Function).
%    We use sfroot to access the chart and replace the script.
%% -------------------------------------------------------------------------
fprintf('[Step 1] Updating NIS MATLAB function with unified logic...\n');

newCode = [...
'function [score, lamda] = compute_NIS(z_gnss, x_kf, P_kf, R)', newline, ...
'%INOAS_DECISION  Unified GNSS/KF switching decision.', newline, ...
'%', newline, ...
'% Combines NIS (statistical consistency) with covariance-based', newline, ...
'% backstop (TRACE logic) into a single decision function.', newline, ...
'%', newline, ...
'% GNSS is ON by default (lamda=1).', newline, ...
'% Switches to KF (lamda=0) when ANY condition holds for N_bad_min steps:', newline, ...
'%   1. NIS > nis_threshold  → innovation inconsistent with filter', newline, ...
'%   2. sigma_pos_kf > sigma_backstop → KF covariance exploded (TRACE logic)', newline, ...
'%', newline, ...
'% Inputs:', newline, ...
'%   z_gnss  (6x1)  raw GNSS measurement  [pos; vel]', newline, ...
'%   x_kf    (6x1)  KF estimated state', newline, ...
'%   P_kf    (6x6)  KF covariance matrix', newline, ...
'%   R       (6x6)  GNSS measurement noise covariance', newline, ...
'%', newline, ...
'% Outputs:', newline, ...
'%   score   scalar  NIS value (for scope monitoring)', newline, ...
'%   lamda   binary  1 = GNSS ON (default),  0 = KF primary', newline, ...
'', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% Parameters', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'nis_threshold  = 16.81;    % chi-squared, 6 DOF, 99% confidence', newline, ...
'sigma_backstop = 120.0;    % [m] position std limit (TRACE backstop)', newline, ...
'N_bad_min  = int32(5);     % consecutive bad epochs  to switch to KF', newline, ...
'N_good_min = int32(15);    % consecutive good epochs to return to GNSS', newline, ...
'', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% Persistent state', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'persistent bad_count good_count gnss_is_bad', newline, ...
'if isempty(bad_count)', newline, ...
'    bad_count   = int32(0);', newline, ...
'    good_count  = int32(0);', newline, ...
'    gnss_is_bad = false;', newline, ...
'end', newline, ...
'', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% Condition 1 - NIS', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'nu    = z_gnss - x_kf;', newline, ...
'S     = 0.5*(P_kf + P_kf.'') + 0.5*(R + R.'');', newline, ...
'S     = S + 1e-9 * eye(6);', newline, ...
'score = nu.'' * (S \ nu);', newline, ...
'nis_bad = score > nis_threshold;', newline, ...
'', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% Condition 2 - TRACE backstop', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'Pr           = P_kf(1:3, 1:3);', newline, ...
'Pr           = 0.5*(Pr + Pr.'');', newline, ...
'sigma_pos_kf = sqrt(max(Pr(1,1) + Pr(2,2) + Pr(3,3), 0.0));', newline, ...
'trace_bad    = sigma_pos_kf > sigma_backstop;', newline, ...
'', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% Combined bad flag', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'gnss_bad_now = nis_bad || trace_bad;', newline, ...
'', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% State machine', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'if ~gnss_is_bad', newline, ...
'    if gnss_bad_now', newline, ...
'        bad_count  = bad_count + int32(1);', newline, ...
'        good_count = int32(0);', newline, ...
'    else', newline, ...
'        bad_count  = int32(max(double(bad_count) - 1, 0));', newline, ...
'    end', newline, ...
'    if bad_count >= N_bad_min', newline, ...
'        gnss_is_bad = true;', newline, ...
'        bad_count   = int32(0);', newline, ...
'        good_count  = int32(0);', newline, ...
'    end', newline, ...
'else', newline, ...
'    if ~gnss_bad_now', newline, ...
'        good_count = good_count + int32(1);', newline, ...
'        bad_count  = int32(0);', newline, ...
'    else', newline, ...
'        good_count = int32(0);', newline, ...
'    end', newline, ...
'    if good_count >= N_good_min', newline, ...
'        gnss_is_bad = false;', newline, ...
'        good_count  = int32(0);', newline, ...
'        bad_count   = int32(0);', newline, ...
'    end', newline, ...
'end', newline, ...
'', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'% Output', newline, ...
'%--------------------------------------------------------------------------', newline, ...
'if gnss_is_bad', newline, ...
'    lamda = 0;', newline, ...
'else', newline, ...
'    lamda = 1;', newline, ...
'end', newline, ...
'', newline, ...
'end'];

% Access the stateflow chart inside the NIS subsystem
try
    rt    = sfroot;
    mdl   = rt.find('-isa', 'Simulink.BlockDiagram', 'Name', modelName);
    % Find all MATLAB function charts
    charts = mdl.find('-isa', 'Stateflow.EMChart');
    found  = false;
    for k = 1:numel(charts)
        % Identify the NIS chart by its current function signature
        if contains(charts(k).Script, 'compute_NIS') || ...
           contains(charts(k).Script, 'z_gnss')
            charts(k).Script = newCode;
            fprintf('  [OK] NIS chart script updated.\n');
            found = true;
            break;
        end
    end
    if ~found
        fprintf('  [WARN] NIS chart not found via sfroot.\n');
        fprintf('         Paste the unified code manually into the NIS block.\n');
    end
catch ME
    fprintf('  [WARN] Could not update via sfroot: %s\n', ME.message);
    fprintf('         Paste the unified code manually into the NIS block.\n');
end

%% -------------------------------------------------------------------------
% 2. Delete wire: TRACE/out:2 --> Switch/in:3
%% -------------------------------------------------------------------------
fprintf('\n[Step 2] Deleting wire TRACE/out:2 --> Switch/in:3...\n');
try
    traceBlocks = findID('TRACE');
    assert(~isempty(traceBlocks), 'TRACE block not found.');
    traceRel  = strrep(traceBlocks{1}, [idPath '/'], '');
    switchBlocks = findID('Switch');
    assert(~isempty(switchBlocks), 'Switch block not found.');

    ph       = get_param(traceBlocks{1}, 'PortHandles');
    lineH    = get_param(ph.Outport(2), 'Line');
    if lineH ~= -1
        delete_line(lineH);
        fprintf('  [OK] Wire deleted.\n');
    else
        fprintf('  [SKIP] No wire on TRACE/out:2.\n');
    end
catch ME
    fprintf('  [WARN] %s\n', ME.message);
end

%% -------------------------------------------------------------------------
% 3. Add Constant block with value 1 and connect to Switch/in:3
%% -------------------------------------------------------------------------
fprintf('\n[Step 3] Adding Constant(1) and connecting to Switch/in:3...\n');
const1Name = 'Constant_GNSS_ON';
const1Path = [idPath '/' const1Name];
try
    already = findID(const1Name);
    if ~isempty(already)
        fprintf('  [SKIP] Constant block already exists.\n');
    else
        % Get Switch position to place Constant nearby
        switchBlocks = findID('Switch');
        swPos = get_param(switchBlocks{1}, 'Position');
        cPos  = [swPos(1)-150, swPos(4)-40, swPos(1)-120, swPos(4)-10];
        add_block('simulink/Sources/Constant', const1Path, ...
            'Value',    '1', ...
            'Position', cPos);
        fprintf('  [OK] Constant(1) block added.\n');
    end
    % Connect Constant(1) --> Switch/in:3
    switchBlocks2 = findID('Switch');
    switchRel = strrep(switchBlocks2{1}, [idPath '/'], '');
    add_line(idPath, [const1Name '/1'], [switchRel '/3'], 'autorouting', 'on');
    fprintf('  [OK] Constant(1) --> Switch/in:3 connected.\n');
catch ME
    fprintf('  [WARN] %s\n', ME.message);
end

%% -------------------------------------------------------------------------
% 4. Delete all wires connected to TRACE block
%% -------------------------------------------------------------------------
fprintf('\n[Step 4] Deleting all wires to/from TRACE...\n');
try
    traceBlocks = findID('TRACE');
    ph = get_param(traceBlocks{1}, 'PortHandles');
    allPorts = [ph.Inport(:); ph.Outport(:)];
    for k = 1:numel(allPorts)
        lh = get_param(allPorts(k), 'Line');
        if lh ~= -1
            delete_line(lh);
            fprintf('  [OK] Wire deleted on port %d.\n', k);
        end
    end
catch ME
    fprintf('  [WARN] %s\n', ME.message);
end

%% -------------------------------------------------------------------------
% 5. Delete TRACE subsystem block
%% -------------------------------------------------------------------------
fprintf('\n[Step 5] Deleting TRACE block...\n');
try
    traceBlocks = findID('TRACE');
    delete_block(traceBlocks{1});
    fprintf('  [OK] TRACE block deleted.\n');
catch ME
    fprintf('  [WARN] %s\n', ME.message);
end

%% -------------------------------------------------------------------------
% 6. Delete Gain and Gain1 blocks (they only fed TRACE)
%    First delete their wires, then the blocks
%% -------------------------------------------------------------------------
fprintf('\n[Step 6] Deleting Gain and Gain1 blocks...\n');
for gname = {'Gain', 'Gain1'}
    gname = gname{1};
    try
        gBlocks = findID(gname);
        if isempty(gBlocks)
            fprintf('  [SKIP] %s not found.\n', gname);
            continue;
        end
        ph = get_param(gBlocks{1}, 'PortHandles');
        allPorts = [ph.Inport(:); ph.Outport(:)];
        for k = 1:numel(allPorts)
            lh = get_param(allPorts(k), 'Line');
            if lh ~= -1
                delete_line(lh);
            end
        end
        delete_block(gBlocks{1});
        fprintf('  [OK] %s deleted.\n', gname);
    catch ME
        fprintf('  [WARN] %s: %s\n', gname, ME.message);
    end
end

%% -------------------------------------------------------------------------
% 7. Delete Scope block (SID 233 — the one that showed TRACE sigma_pos)
%    Keep Scope1 (shows NIS score for monitoring)
%% -------------------------------------------------------------------------
fprintf('\n[Step 7] Deleting TRACE Scope...\n');
try
    % Find scope not connected to NIS output
    allScopes = find_system(idPath, 'SearchDepth', 1, 'BlockType', 'Scope');
    for k = 1:numel(allScopes)
        sname = get_param(allScopes{k}, 'Name');
        ph    = get_param(allScopes{k}, 'PortHandles');
        lh    = get_param(ph.Inport(1), 'Line');
        % Check if this scope is connected to NIS/out:1 — keep that one
        % The TRACE scope has no line (after TRACE deletion) or a dangling line
        if lh == -1
            delete_block(allScopes{k});
            fprintf('  [OK] Scope "%s" deleted (was connected to TRACE).\n', sname);
        else
            fprintf('  [KEEP] Scope "%s" kept (connected to NIS score).\n', sname);
        end
    end
catch ME
    fprintf('  [WARN] %s\n', ME.message);
end

%% -------------------------------------------------------------------------
% 8. Save
%% -------------------------------------------------------------------------
fprintf('\n--- Saving model ---\n');
try
    save_system(modelName);
    fprintf('[OK] Saved: %s.slx\n', modelName);
catch ME
    fprintf('[ERROR] %s\n', ME.message);
end

fprintf('\n============================================================\n');
fprintf(' Done. Final wiring inside INSTRUMENT DECISION1:\n\n');
fprintf('   X_gnss  -->\n');
fprintf('   X_est   --> NIS (unified) --> score --> Scope1 (monitor)\n');
fprintf('   P_kf    -->               --> lamda --> NOT --> Switch/in:1\n');
fprintf('   Q_gnss  -->\n');
fprintf('                     Constant(0) --> Switch/in:2 (force KF)\n');
fprintf('                     Constant(1) --> Switch/in:3 (keep GNSS)\n');
fprintf('                     Switch/out  --> lamda output\n');
fprintf('\n Next: run simulation for 28,000s and check Scope1\n');
fprintf('       (NIS should spike above 16.81 at t≈27,010s)\n');
fprintf('============================================================\n');
